# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication/v1alpha2/policy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from authentication.v1alpha2 import authenticator_pb2 as authentication_dot_v1alpha2_dot_authenticator__pb2
from common.v1beta1 import selector_pb2 as common_dot_v1beta1_dot_selector__pb2
from common.v1beta1 import match_pb2 as common_dot_v1beta1_dot_match__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='authentication/v1alpha2/policy.proto',
  package='istio.authentication.v1alpha2',
  syntax='proto3',
  serialized_pb=_b('\n$authentication/v1alpha2/policy.proto\x12\x1distio.authentication.v1alpha2\x1a+authentication/v1alpha2/authenticator.proto\x1a\x1d\x63ommon/v1beta1/selector.proto\x1a\x1a\x63ommon/v1beta1/match.proto\"\xcf\x02\n\x14\x41uthenticationPolicy\x12\x30\n\x08selector\x18\x01 \x01(\x0b\x32\x1e.istio.common.v1beta1.Selector\x12_\n\x0e\x61uthenticators\x18\x02 \x03(\x0b\x32G.istio.authentication.v1alpha2.AuthenticationPolicy.AuthenticatorsEntry\x12?\n\x05rules\x18\x03 \x03(\x0b\x32\x30.istio.authentication.v1alpha2.AuthenticatorRule\x1a\x63\n\x13\x41uthenticatorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12;\n\x05value\x18\x02 \x01(\x0b\x32,.istio.authentication.v1alpha2.Authenticator:\x02\x38\x01\"\x8b\x01\n\x11\x41uthenticatorRule\x12\x33\n\x05match\x18\x01 \x01(\x0b\x32$.istio.authentication.v1alpha2.Match\x12\x41\n\x08\x66irst_of\x18\x02 \x03(\x0b\x32/.istio.authentication.v1alpha2.AuthenticatorRef\")\n\x10\x41uthenticatorRef\x12\x15\n\rauthenticator\x18\x01 \x01(\t\"E\n\x05Match\x12\x0c\n\x04port\x18\x01 \x01(\r\x12.\n\x03uri\x18\x02 \x01(\x0b\x32!.istio.common.v1beta1.StringMatchB&Z$istio.io/api/authentication/v1alpha2b\x06proto3')
  ,
  dependencies=[authentication_dot_v1alpha2_dot_authenticator__pb2.DESCRIPTOR,common_dot_v1beta1_dot_selector__pb2.DESCRIPTOR,common_dot_v1beta1_dot_match__pb2.DESCRIPTOR,])




_AUTHENTICATIONPOLICY_AUTHENTICATORSENTRY = _descriptor.Descriptor(
  name='AuthenticatorsEntry',
  full_name='istio.authentication.v1alpha2.AuthenticationPolicy.AuthenticatorsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='istio.authentication.v1alpha2.AuthenticationPolicy.AuthenticatorsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='istio.authentication.v1alpha2.AuthenticationPolicy.AuthenticatorsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=511,
)

_AUTHENTICATIONPOLICY = _descriptor.Descriptor(
  name='AuthenticationPolicy',
  full_name='istio.authentication.v1alpha2.AuthenticationPolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='istio.authentication.v1alpha2.AuthenticationPolicy.selector', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authenticators', full_name='istio.authentication.v1alpha2.AuthenticationPolicy.authenticators', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rules', full_name='istio.authentication.v1alpha2.AuthenticationPolicy.rules', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AUTHENTICATIONPOLICY_AUTHENTICATORSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=511,
)


_AUTHENTICATORRULE = _descriptor.Descriptor(
  name='AuthenticatorRule',
  full_name='istio.authentication.v1alpha2.AuthenticatorRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='match', full_name='istio.authentication.v1alpha2.AuthenticatorRule.match', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_of', full_name='istio.authentication.v1alpha2.AuthenticatorRule.first_of', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=653,
)


_AUTHENTICATORREF = _descriptor.Descriptor(
  name='AuthenticatorRef',
  full_name='istio.authentication.v1alpha2.AuthenticatorRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authenticator', full_name='istio.authentication.v1alpha2.AuthenticatorRef.authenticator', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=696,
)


_MATCH = _descriptor.Descriptor(
  name='Match',
  full_name='istio.authentication.v1alpha2.Match',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='istio.authentication.v1alpha2.Match.port', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uri', full_name='istio.authentication.v1alpha2.Match.uri', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=698,
  serialized_end=767,
)

_AUTHENTICATIONPOLICY_AUTHENTICATORSENTRY.fields_by_name['value'].message_type = authentication_dot_v1alpha2_dot_authenticator__pb2._AUTHENTICATOR
_AUTHENTICATIONPOLICY_AUTHENTICATORSENTRY.containing_type = _AUTHENTICATIONPOLICY
_AUTHENTICATIONPOLICY.fields_by_name['selector'].message_type = common_dot_v1beta1_dot_selector__pb2._SELECTOR
_AUTHENTICATIONPOLICY.fields_by_name['authenticators'].message_type = _AUTHENTICATIONPOLICY_AUTHENTICATORSENTRY
_AUTHENTICATIONPOLICY.fields_by_name['rules'].message_type = _AUTHENTICATORRULE
_AUTHENTICATORRULE.fields_by_name['match'].message_type = _MATCH
_AUTHENTICATORRULE.fields_by_name['first_of'].message_type = _AUTHENTICATORREF
_MATCH.fields_by_name['uri'].message_type = common_dot_v1beta1_dot_match__pb2._STRINGMATCH
DESCRIPTOR.message_types_by_name['AuthenticationPolicy'] = _AUTHENTICATIONPOLICY
DESCRIPTOR.message_types_by_name['AuthenticatorRule'] = _AUTHENTICATORRULE
DESCRIPTOR.message_types_by_name['AuthenticatorRef'] = _AUTHENTICATORREF
DESCRIPTOR.message_types_by_name['Match'] = _MATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthenticationPolicy = _reflection.GeneratedProtocolMessageType('AuthenticationPolicy', (_message.Message,), dict(

  AuthenticatorsEntry = _reflection.GeneratedProtocolMessageType('AuthenticatorsEntry', (_message.Message,), dict(
    DESCRIPTOR = _AUTHENTICATIONPOLICY_AUTHENTICATORSENTRY,
    __module__ = 'authentication.v1alpha2.policy_pb2'
    # @@protoc_insertion_point(class_scope:istio.authentication.v1alpha2.AuthenticationPolicy.AuthenticatorsEntry)
    ))
  ,
  DESCRIPTOR = _AUTHENTICATIONPOLICY,
  __module__ = 'authentication.v1alpha2.policy_pb2'
  # @@protoc_insertion_point(class_scope:istio.authentication.v1alpha2.AuthenticationPolicy)
  ))
_sym_db.RegisterMessage(AuthenticationPolicy)
_sym_db.RegisterMessage(AuthenticationPolicy.AuthenticatorsEntry)

AuthenticatorRule = _reflection.GeneratedProtocolMessageType('AuthenticatorRule', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATORRULE,
  __module__ = 'authentication.v1alpha2.policy_pb2'
  # @@protoc_insertion_point(class_scope:istio.authentication.v1alpha2.AuthenticatorRule)
  ))
_sym_db.RegisterMessage(AuthenticatorRule)

AuthenticatorRef = _reflection.GeneratedProtocolMessageType('AuthenticatorRef', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATORREF,
  __module__ = 'authentication.v1alpha2.policy_pb2'
  # @@protoc_insertion_point(class_scope:istio.authentication.v1alpha2.AuthenticatorRef)
  ))
_sym_db.RegisterMessage(AuthenticatorRef)

Match = _reflection.GeneratedProtocolMessageType('Match', (_message.Message,), dict(
  DESCRIPTOR = _MATCH,
  __module__ = 'authentication.v1alpha2.policy_pb2'
  # @@protoc_insertion_point(class_scope:istio.authentication.v1alpha2.Match)
  ))
_sym_db.RegisterMessage(Match)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z$istio.io/api/authentication/v1alpha2'))
_AUTHENTICATIONPOLICY_AUTHENTICATORSENTRY.has_options = True
_AUTHENTICATIONPOLICY_AUTHENTICATORSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
